---
abstract: 'Simple asynchronous finger client and server'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Finger
recommends:
  EV: 0
requires:
  AnyEvent: 0
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Exporter: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/anyevent-finger/issues
  homepage: http://perl.wdlabs.com/AnyEvent-Finger/
  repository: git://github.com/plicease/anyevent-finger.git
version: 0.08
